#!/usr/bin/swift sh
import Bake
import BakeXcode  // https://codeberg.org/openbakery/bake.git == main
import Foundation

let xcodeVersion = 26
let scheme = "PinLayout"
let deviceName = "iPhone 17 Pro"
let onlyTesting = [String]()


if CommandLine.arguments.count > 1 {
	if CommandLine.arguments[1] == "--result" {
		await printResult()
		exit(0)
	}
}

@discardableResult
func handle(error: Error) -> Int32 {
	if let commandError = error as? Command.CommandError {
		switch commandError {
			case .failedExecution(let terminationStatus, _):
				print("error: \(commandError)")
				return terminationStatus
		}
	}
	return 0
}

func printResult(json: Bool = false) async {
	do {
		let commandRunner = CommandRunner()
		var arguments = ["build/Logs/Test"]
		if json {
			arguments.append("--json")
		}
		try await commandRunner.run("./scripts/xcresult_parser.swift", arguments: arguments)
	} catch {
		handle(error: error)
	}
}

func runCarthage(xcode: Xcode) async {
	do {

		let commandRunner = xcode.commandRunner
		await try commandRunner.run(
			"/opt/homebrew/bin/carthage", arguments: ["bootstrap", "--platform", "iOS", "--use-xcframeworks", "--cache-builds"])

	} catch {
		let code = handle(error: error)
		if code > 0 {
			exit(code)
		}
	}
}

func delete(url: URL) async {
	let fileManager = FileManager.default
	do {
		try fileManager.removeItem(at: url)
		print("Directory deleted successfully")
	} catch {
		print("Error deleting directory: \(error)")
	}
}


func clean() async {
	await delete(url: URL(fileURLWithPath: "build"))
}

guard let xcode = try await Xcode(version: xcodeVersion) else {
	print("No Xcode \(xcodeVersion) found")
	exit(1)
}

print("Using: \(xcode)")
await delete(url: URL(fileURLWithPath: "build/Logs/Test"))

let simulatorControl = SimulatorControl(commandRunner: xcode.commandRunner)

guard var simulator = try await simulatorControl.simulator(name: deviceName, fuzzy: false) else {
	print("simulator not found for: \(deviceName)")
	exit(1)
}

var exitCode: Int32 = 0
do {
	let xcodebuild = Xcodebuild(
		command: .test,
		scheme: scheme,
		destination: simulator.destination,
		onlyTest: onlyTesting,
		retryTestsOnFailure: true,
		xcode: xcode)

	print("Build output goes to: \(xcodebuild.path)")

	try await xcodebuild.execute()

} catch {
	exitCode = handle(error: error)
}

await printResult()
exit(exitCode)
